# Generated by Django 3.2.1 on 2021-09-10 13:55

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20210910_2151'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.AlterField(
            model_name='goods',
            name='new',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='goods',
            name='strategy',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
