# Generated by Django 3.2.1 on 2021-09-10 13:58

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0005_auto_20210910_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='new',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='商品新闻'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='strategy',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='商品攻略'),
        ),
    ]
